--Generated with Kogitsune's Resource Generator
resource.AddFile( "materials/trails/vaporgrid.vmt" )
resource.AddFile( "materials/trails/vaporgrid.vtf" )
resource.AddFile( "materials/trails/ausmoney.vmt" )
resource.AddFile( "materials/trails/ausmoney.vtf" )
resource.AddFile( "materials/trails/australian_flag.vmt" )
resource.AddFile( "materials/trails/australian_flag.vtf" )
resource.AddFile( "materials/trails/awesomeface.vmt" )
resource.AddFile( "materials/trails/awesomeface.vtf" )
resource.AddFile( "materials/trails/batman.vmt" )
resource.AddFile( "materials/trails/batman.vtf" )
resource.AddFile( "materials/trails/biscuitbase.vmt" )
resource.AddFile( "materials/trails/biscuitbase.vtf" )
resource.AddFile( "materials/trails/checker.vmt" )
resource.AddFile( "materials/trails/checker.vtf" )
resource.AddFile( "materials/trails/color.vmt" )
resource.AddFile( "materials/trails/creeper.vmt" )
resource.AddFile( "materials/trails/creeper.vtf" )
resource.AddFile( "materials/trails/dogetrail.vmt" )
resource.AddFile( "materials/trails/dogetrail.vtf" )
resource.AddFile( "materials/trails/gameredacted_trail.vmt" )
resource.AddFile( "materials/trails/gameredacted_trail.vtf" )
resource.AddFile( "materials/trails/lennytrail.vmt" )
resource.AddFile( "materials/trails/lennytrail.vtf" )
resource.AddFile( "materials/trails/pedo.vmt" )
resource.AddFile( "materials/trails/pedo.vtf" )
resource.AddFile( "materials/trails/rainbow_gr.vmt" )
resource.AddFile( "materials/trails/rainbow_gr.vtf" )
resource.AddFile( "materials/trails/robbie.vmt" )
resource.AddFile( "materials/trails/robbie.vtf" )
resource.AddFile( "models/astronauthelmet/astronauthelmet.dx80.vtx" )
resource.AddFile( "models/astronauthelmet/astronauthelmet.dx90.vtx" )
resource.AddFile( "models/astronauthelmet/astronauthelmet.mdl" )
resource.AddFile( "models/astronauthelmet/astronauthelmet.phy" )
resource.AddFile( "models/astronauthelmet/astronauthelmet.sw.vtx" )
resource.AddFile( "models/astronauthelmet/astronauthelmet.vvd" )
resource.AddFile( "models/cakehat/cakehat.dx80.vtx" )
resource.AddFile( "models/cakehat/cakehat.dx90.vtx" )
resource.AddFile( "models/cakehat/cakehat.mdl" )
resource.AddFile( "models/cakehat/cakehat.phy" )
resource.AddFile( "models/cakehat/cakehat.sw.vtx" )
resource.AddFile( "models/cakehat/cakehat.vvd" )
resource.AddFile( "models/duncehat/duncehat.dx80.vtx" )
resource.AddFile( "models/duncehat/duncehat.dx90.vtx" )
resource.AddFile( "models/duncehat/duncehat.mdl" )
resource.AddFile( "models/duncehat/duncehat.phy" )
resource.AddFile( "models/duncehat/duncehat.sw.vtx" )
resource.AddFile( "models/duncehat/duncehat.vvd" )
resource.AddFile( "models/gmod_tower/3dglasses.dx80.vtx" )
resource.AddFile( "models/gmod_tower/3dglasses.dx90.vtx" )
resource.AddFile( "models/gmod_tower/3dglasses.mdl" )
resource.AddFile( "models/gmod_tower/3dglasses.sw.vtx" )
resource.AddFile( "models/gmod_tower/3dglasses.vvd" )
resource.AddFile( "models/gmod_tower/afro.dx80.vtx" )
resource.AddFile( "models/gmod_tower/afro.dx90.vtx" )
resource.AddFile( "models/gmod_tower/afro.mdl" )
resource.AddFile( "models/gmod_tower/afro.sw.vtx" )
resource.AddFile( "models/gmod_tower/afro.vvd" )
resource.AddFile( "models/gmod_tower/aviators.dx80.vtx" )
resource.AddFile( "models/gmod_tower/aviators.dx90.vtx" )
resource.AddFile( "models/gmod_tower/aviators.mdl" )
resource.AddFile( "models/gmod_tower/aviators.sw.vtx" )
resource.AddFile( "models/gmod_tower/aviators.vvd" )
resource.AddFile( "models/gmod_tower/catears.dx80.vtx" )
resource.AddFile( "models/gmod_tower/catears.dx90.vtx" )
resource.AddFile( "models/gmod_tower/catears.mdl" )
resource.AddFile( "models/gmod_tower/catears.sw.vtx" )
resource.AddFile( "models/gmod_tower/catears.vvd" )
resource.AddFile( "models/gmod_tower/fedorahat.dx80.vtx" )
resource.AddFile( "models/gmod_tower/fedorahat.dx90.vtx" )
resource.AddFile( "models/gmod_tower/fedorahat.mdl" )
resource.AddFile( "models/gmod_tower/fedorahat.sw.vtx" )
resource.AddFile( "models/gmod_tower/fedorahat.vvd" )
resource.AddFile( "models/gmod_tower/kfcbucket.dx80.vtx" )
resource.AddFile( "models/gmod_tower/kfcbucket.dx90.vtx" )
resource.AddFile( "models/gmod_tower/kfcbucket.mdl" )
resource.AddFile( "models/gmod_tower/kfcbucket.sw.vtx" )
resource.AddFile( "models/gmod_tower/kfcbucket.vvd" )
resource.AddFile( "models/gmod_tower/klienerglasses.dx80.vtx" )
resource.AddFile( "models/gmod_tower/klienerglasses.dx90.vtx" )
resource.AddFile( "models/gmod_tower/klienerglasses.mdl" )
resource.AddFile( "models/gmod_tower/klienerglasses.sw.vtx" )
resource.AddFile( "models/gmod_tower/klienerglasses.vvd" )
resource.AddFile( "models/gmod_tower/linkhat.dx80.vtx" )
resource.AddFile( "models/gmod_tower/linkhat.dx90.vtx" )
resource.AddFile( "models/gmod_tower/linkhat.mdl" )
resource.AddFile( "models/gmod_tower/linkhat.sw.vtx" )
resource.AddFile( "models/gmod_tower/linkhat.vvd" )
resource.AddFile( "models/gmod_tower/majorasmask.dx80.vtx" )
resource.AddFile( "models/gmod_tower/majorasmask.dx90.vtx" )
resource.AddFile( "models/gmod_tower/majorasmask.mdl" )
resource.AddFile( "models/gmod_tower/majorasmask.sw.vtx" )
resource.AddFile( "models/gmod_tower/majorasmask.vvd" )
resource.AddFile( "models/gmod_tower/midnahat.dx80.vtx" )
resource.AddFile( "models/gmod_tower/midnahat.dx90.vtx" )
resource.AddFile( "models/gmod_tower/midnahat.mdl" )
resource.AddFile( "models/gmod_tower/midnahat.sw.vtx" )
resource.AddFile( "models/gmod_tower/midnahat.vvd" )
resource.AddFile( "models/gmod_tower/partyhat.dx80.vtx" )
resource.AddFile( "models/gmod_tower/partyhat.dx90.vtx" )
resource.AddFile( "models/gmod_tower/partyhat.mdl" )
resource.AddFile( "models/gmod_tower/partyhat.sw.vtx" )
resource.AddFile( "models/gmod_tower/partyhat.vvd" )
resource.AddFile( "models/gmod_tower/seusshat.dx80.vtx" )
resource.AddFile( "models/gmod_tower/seusshat.dx90.vtx" )
resource.AddFile( "models/gmod_tower/seusshat.mdl" )
resource.AddFile( "models/gmod_tower/seusshat.sw.vtx" )
resource.AddFile( "models/gmod_tower/seusshat.vvd" )
resource.AddFile( "models/gmod_tower/sombrero.dx80.vtx" )
resource.AddFile( "models/gmod_tower/sombrero.dx90.vtx" )
resource.AddFile( "models/gmod_tower/sombrero.mdl" )
resource.AddFile( "models/gmod_tower/sombrero.sw.vtx" )
resource.AddFile( "models/gmod_tower/sombrero.vvd" )
resource.AddFile( "models/gmod_tower/starglasses.dx80.vtx" )
resource.AddFile( "models/gmod_tower/starglasses.dx90.vtx" )
resource.AddFile( "models/gmod_tower/starglasses.mdl" )
resource.AddFile( "models/gmod_tower/starglasses.sw.vtx" )
resource.AddFile( "models/gmod_tower/starglasses.vvd" )
resource.AddFile( "models/gmod_tower/toetohat.dx80.vtx" )
resource.AddFile( "models/gmod_tower/toetohat.dx90.vtx" )
resource.AddFile( "models/gmod_tower/toetohat.mdl" )
resource.AddFile( "models/gmod_tower/toetohat.sw.vtx" )
resource.AddFile( "models/gmod_tower/toetohat.vvd" )
resource.AddFile( "models/gmod_tower/tophat.dx80.vtx" )
resource.AddFile( "models/gmod_tower/tophat.dx90.vtx" )
resource.AddFile( "models/gmod_tower/tophat.mdl" )
resource.AddFile( "models/gmod_tower/tophat.sw.vtx" )
resource.AddFile( "models/gmod_tower/tophat.vvd" )
resource.AddFile( "models/gmod_tower/witchhat.dx80.vtx" )
resource.AddFile( "models/gmod_tower/witchhat.dx90.vtx" )
resource.AddFile( "models/gmod_tower/witchhat.mdl" )
resource.AddFile( "models/gmod_tower/witchhat.sw.vtx" )
resource.AddFile( "models/gmod_tower/witchhat.vvd" )
resource.AddFile( "models/piratehat/piratehat.dx80.vtx" )
resource.AddFile( "models/piratehat/piratehat.dx90.vtx" )
resource.AddFile( "models/piratehat/piratehat.mdl" )
resource.AddFile( "models/piratehat/piratehat.phy" )
resource.AddFile( "models/piratehat/piratehat.sw.vtx" )
resource.AddFile( "models/piratehat/piratehat.vvd" )
resource.AddFile( "models/sam/antlers.dx80.vtx" )
resource.AddFile( "models/sam/antlers.dx90.vtx" )
resource.AddFile( "models/sam/antlers.mdl" )
resource.AddFile( "models/sam/antlers.sw.vtx" )
resource.AddFile( "models/sam/antlers.vvd" )
resource.AddFile( "models/sam/drinkcap.dx80.vtx" )
resource.AddFile( "models/sam/drinkcap.dx90.vtx" )
resource.AddFile( "models/sam/drinkcap.mdl" )
resource.AddFile( "models/sam/drinkcap.sw.vtx" )
resource.AddFile( "models/sam/drinkcap.vvd" )
resource.AddFile( "models/santa/santa.dx80.vtx" )
resource.AddFile( "models/santa/santa.dx90.vtx" )
resource.AddFile( "models/santa/santa.mdl" )
resource.AddFile( "models/santa/santa.sw.vtx" )
resource.AddFile( "models/santa/santa.vvd" )
resource.AddFile( "models/vikinghelmet/vikinghelmet.dx80.vtx" )
resource.AddFile( "models/vikinghelmet/vikinghelmet.dx90.vtx" )
resource.AddFile( "models/vikinghelmet/vikinghelmet.mdl" )
resource.AddFile( "models/vikinghelmet/vikinghelmet.phy" )
resource.AddFile( "models/vikinghelmet/vikinghelmet.sw.vtx" )
resource.AddFile( "models/vikinghelmet/vikinghelmet.vvd" )
resource.AddFile( "materials/models/astronauthelmet/astroglass.vmt" )
resource.AddFile( "materials/models/astronauthelmet/astroglass.vtf" )
resource.AddFile( "materials/models/astronauthelmet/astrohelmet.vmt" )
resource.AddFile( "materials/models/astronauthelmet/astrohelmet.vtf" )
resource.AddFile( "materials/models/cakehat/cakehat.vmt" )
resource.AddFile( "materials/models/cakehat/cakehat.vtf" )
resource.AddFile( "materials/models/cakehat/cakehat_exp.vtf" )
resource.AddFile( "materials/models/cakehat/cakehat_n.vtf" )
resource.AddFile( "materials/models/duncehat/duncehat.vmt" )
resource.AddFile( "materials/models/duncehat/duncehat.vtf" )
resource.AddFile( "materials/models/gmod_tower/3dcolors.vmt" )
resource.AddFile( "materials/models/gmod_tower/3dcolors.vtf" )
resource.AddFile( "materials/models/gmod_tower/3dglasses.vmt" )
resource.AddFile( "materials/models/gmod_tower/3dglasses.vtf" )
resource.AddFile( "materials/models/gmod_tower/afro.vmt" )
resource.AddFile( "materials/models/gmod_tower/afro.vtf" )
resource.AddFile( "materials/models/gmod_tower/afro2.vmt" )
resource.AddFile( "materials/models/gmod_tower/afro2.vtf" )
resource.AddFile( "materials/models/gmod_tower/afro_pick.vmt" )
resource.AddFile( "materials/models/gmod_tower/afro_pick.vtf" )
resource.AddFile( "materials/models/gmod_tower/aviators.vmt" )
resource.AddFile( "materials/models/gmod_tower/aviators.vtf" )
resource.AddFile( "materials/models/gmod_tower/aviators_g.vmt" )
resource.AddFile( "materials/models/gmod_tower/aviators_g.vtf" )
resource.AddFile( "materials/models/gmod_tower/catears.vmt" )
resource.AddFile( "materials/models/gmod_tower/catears.vtf" )
resource.AddFile( "materials/models/gmod_tower/drinkcap.vmt" )
resource.AddFile( "materials/models/gmod_tower/drinkcap.vtf" )
resource.AddFile( "materials/models/gmod_tower/drinkcap_n.vtf" )
resource.AddFile( "materials/models/gmod_tower/drinkcap_p.vtf" )
resource.AddFile( "materials/models/gmod_tower/fedorahat.vmt" )
resource.AddFile( "materials/models/gmod_tower/fedorahat.vtf" )
resource.AddFile( "materials/models/gmod_tower/fedorahat2.vmt" )
resource.AddFile( "materials/models/gmod_tower/fedorahat2.vtf" )
resource.AddFile( "materials/models/gmod_tower/kfcbucket.vmt" )
resource.AddFile( "materials/models/gmod_tower/kfcbucket.vtf" )
resource.AddFile( "materials/models/gmod_tower/linkhat.vmt" )
resource.AddFile( "materials/models/gmod_tower/linkhat.vtf" )
resource.AddFile( "materials/models/gmod_tower/majorasmask.vmt" )
resource.AddFile( "materials/models/gmod_tower/majorasmask.vtf" )
resource.AddFile( "materials/models/gmod_tower/midnahat.vmt" )
resource.AddFile( "materials/models/gmod_tower/midnahat.vtf" )
resource.AddFile( "materials/models/gmod_tower/partyhat.vmt" )
resource.AddFile( "materials/models/gmod_tower/partyhat.vtf" )
resource.AddFile( "materials/models/gmod_tower/santahat.vmt" )
resource.AddFile( "materials/models/gmod_tower/santahat.vtf" )
resource.AddFile( "materials/models/gmod_tower/seusshat.vmt" )
resource.AddFile( "materials/models/gmod_tower/seusshat.vtf" )
resource.AddFile( "materials/models/gmod_tower/sombrero.vmt" )
resource.AddFile( "materials/models/gmod_tower/sombrero.vtf" )
resource.AddFile( "materials/models/gmod_tower/starglass.vmt" )
resource.AddFile( "materials/models/gmod_tower/starglass.vtf" )
resource.AddFile( "materials/models/gmod_tower/starglasses.vmt" )
resource.AddFile( "materials/models/gmod_tower/starglasses.vtf" )
resource.AddFile( "materials/models/gmod_tower/straws.vmt" )
resource.AddFile( "materials/models/gmod_tower/toetohat.vmt" )
resource.AddFile( "materials/models/gmod_tower/toetohat.vtf" )
resource.AddFile( "materials/models/gmod_tower/tophat.vmt" )
resource.AddFile( "materials/models/gmod_tower/tophat.vtf" )
resource.AddFile( "materials/models/gmod_tower/witchhat.vmt" )
resource.AddFile( "materials/models/gmod_tower/witchhat.vtf" )
resource.AddFile( "materials/models/piratehat/piratehat.vmt" )
resource.AddFile( "materials/models/piratehat/piratehat.vtf" )
resource.AddFile( "materials/models/sam/antlers.vmt" )
resource.AddFile( "materials/models/sam/antlers.vtf" )
resource.AddFile( "materials/models/sam/antlers_n.vtf" )
resource.AddFile( "materials/models/sam/antlers_s.vtf" )
resource.AddFile( "materials/models/sam/drinkcap.vmt" )
resource.AddFile( "materials/models/sam/drinkcap.vtf" )
resource.AddFile( "materials/models/sam/drinkcap_n.vtf" )
resource.AddFile( "materials/models/sam/drinkcap_p.vtf" )
resource.AddFile( "materials/models/sam/straws.vmt" )
resource.AddFile( "materials/models/santa/ball.vmt" )
resource.AddFile( "materials/models/santa/ball.vtf" )
resource.AddFile( "materials/models/santa/santa.vmt" )
resource.AddFile( "materials/models/santa/santa.vtf" )
resource.AddFile( "materials/models/vikinghelmet/vikinghelmet.vmt" )
resource.AddFile( "materials/models/vikinghelmet/vikinghelmet.vtf" )
resource.AddFile( "materials/models/vikinghelmet/vikinghelmet_normal.vtf" )


-- taunts
resource.AddFile( "sound/mlg/airhorn.mp3" )
resource.AddFile( "sound/mlg/momgetthecamera.wav" )
resource.AddFile( "sound/mlg/triple.mp3" )
resource.AddFile( "sound/mlg/wombocombo.wav" )
resource.AddFile( "sound/mlg/wow.wav" )
resource.AddFile( "sound/taunts/nootnoot.ogg" )

--horse
resource.AddFile( "materials/models/horsie/horsie.vmt" )
resource.AddFile( "materials/models/horsie/horsie.vtf" )
resource.AddFile( "materials/models/horsie/horsie_b.vmt" )
resource.AddFile( "materials/models/horsie/horsie_b.vtf" )
resource.AddFile( "materials/models/horsie/horsie_c.vmt" )
resource.AddFile( "materials/models/horsie/horsie_c.vtf" )
resource.AddFile( "materials/models/horsie/horsie_normal.vtf" )
resource.AddFile( "models/horsie/horsiemask.mdl" )

--christmeme
resource.AddFile( "materials/trails/candycane_1.vmt" )
resource.AddFile( "materials/trails/candycane_1.vtf" )

resource.AddFile( "materials/trails/candycane_2.vmt" )
resource.AddFile( "materials/trails/candycane_2.vtf" )

-- new taunts dec 2015
local taunts = {
	"ram_stomach",
	"say_my_name",
	"seduce_me",
	"sue_me",
	"tearing_lisa",
	"teleport_bread",
	"this_is_illegal_you_know",
	"you_sob",
	"another_one",
	"appreciate",
	"asshole_tv",
	"bacon",
	"cancer",
	"cant_handle_success",
	"communism",
	"dear_god",
	"death_alternative",
	"dickwad",
	"excuse2",
	"hasta_la_vista",
	"kill_you_last",
	"kiss_mothers_behind",
	"now_good_time",
	"pizza",
	"quickly",
	"121gigawatts",
	"booyouwhore",
	"nooo",
	"nootnoot",
	"smams",
	"sorrydave",
	"xfiles",
	"youmaniacs",
}

for k,v in ipairs(taunts) do
	resource.AddFile( "sound/taunts/"..v..".ogg" )
end

-- angel wings
resource.AddFile("models/sinful/angel_wings.mdl")
resource.AddFile("models/sinful/angel_wings.dx80.vtx")
resource.AddFile("models/sinful/angel_wings.dx90.vtx")
resource.AddFile("models/sinful/angel_wings.sw.vtx")
resource.AddFile("models/sinful/angel_wings.vvd")
resource.AddFile("materials/models/sinful/angel_wings/wings.vmt")
resource.AddFile("materials/models/sinful/angel_wings/wings_normal.vtf")
resource.AddFile("materials/models/sinful/angel_wings/wings_exponent.vtf")

-- tf2 gold and ice
resource.AddFile( "materials/cubemaps/cubemap_gold001.vtf" )
resource.AddFile( "materials/effects/cubemapper.vtf" )
resource.AddFile( "materials/effects/tiledfire/firelayeredslowtiled512.vtf" )
resource.AddFile( "materials/models/effects/flat_normal.vtf" )
resource.AddFile( "materials/models/player/shared/gold_player.vmt" )
resource.AddFile( "materials/models/player/shared/gold_player.vtf" )
resource.AddFile( "materials/models/player/shared/ice_player.vmt" )
resource.AddFile( "materials/models/player/shared/ice_player.vtf" )
resource.AddFile( "materials/models/player/shared/ice_player_lightwarp.vtf" )
resource.AddFile( "materials/models/player/shared/ice_player_warp.vtf" )
resource.AddFile( "materials/models/weapons/c_items/c_xms_cold_shoulder_normal.vtf" )

-- tf2 crate sounds
resource.AddFile( "sound/crates/item_open_crate_short.ogg" )
resource.AddFile( "sound/crates/killstreak.ogg" )

-- apb hair models

resource.AddFile( "materials/models/jessev92/apb/afro.vmt" )
resource.AddFile( "materials/models/jessev92/apb/afro.vtf" )
resource.AddFile( "materials/models/jessev92/apb/afro_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/anime1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/anime1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/anime1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/anime2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/anime2.vtf" )
resource.AddFile( "materials/models/jessev92/apb/anime2_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/dreadlocks.vmt" )
resource.AddFile( "materials/models/jessev92/apb/dreadlocks.vtf" )
resource.AddFile( "materials/models/jessev92/apb/dreadlocks_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/ducktail1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/ducktail1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/ducktail1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/ducktail2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/ducktail2.vtf" )
resource.AddFile( "materials/models/jessev92/apb/emo1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/emo1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/fins1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/fins1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/fins1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/frontflip1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/frontflip1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/frontflip1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/loverboy1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/loverboy1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/loverboy1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/mohawk1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/mohawk1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/mohawk1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/mohawk2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/mohawk2.vtf" )
resource.AddFile( "materials/models/jessev92/apb/mohawk2_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/mohawk3.vmt" )
resource.AddFile( "materials/models/jessev92/apb/mohawk3.vtf" )
resource.AddFile( "materials/models/jessev92/apb/mohawk3_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/partedleftlong1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/partedleftlong1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/partedleftlong1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/partedmiddle1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/partedmiddle1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/partedmiddle1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/partedright1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/partedright1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/partedright1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/ponytail1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/ponytail1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/ponytail1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/shoulder1.vmt" )
resource.AddFile( "materials/models/jessev92/apb/shoulder1.vtf" )
resource.AddFile( "materials/models/jessev92/apb/shoulder1_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/shoulder2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/shoulder2.vtf" )
resource.AddFile( "materials/models/jessev92/apb/shoulder2_2.vmt" )
resource.AddFile( "materials/models/jessev92/apb/slickedback.vmt" )
resource.AddFile( "materials/models/jessev92/apb/slickedback.vtf" )
resource.AddFile( "materials/models/jessev92/apb/slickedback_2.vmt" )
resource.AddFile( "models/jessev92/apb/hair_afro1.mdl" )
resource.AddFile( "models/jessev92/apb/hair_anime1.mdl" )
resource.AddFile( "models/jessev92/apb/hair_anime2.mdl" )
resource.AddFile( "models/jessev92/apb/hair_dreadlocks.mdl" )
resource.AddFile( "models/jessev92/apb/hair_ducktail1.mdl" )
resource.AddFile( "models/jessev92/apb/hair_ducktail2.mdl" )
resource.AddFile( "models/jessev92/apb/hair_emo1.mdl" )
resource.AddFile( "models/jessev92/apb/hair_fins1.mdl" )
resource.AddFile( "models/jessev92/apb/hair_frontflip1.mdl" )
resource.AddFile( "models/jessev92/apb/hair_loverboy.mdl" )
resource.AddFile( "models/jessev92/apb/hair_mohawk1.mdl" )
resource.AddFile( "models/jessev92/apb/hair_mohawk2.mdl" )
resource.AddFile( "models/jessev92/apb/hair_mohawk3.mdl" )
resource.AddFile( "models/jessev92/apb/hair_partedleft.mdl" )
resource.AddFile( "models/jessev92/apb/hair_partedmiddle.mdl" )
resource.AddFile( "models/jessev92/apb/hair_partedright.mdl" )
resource.AddFile( "models/jessev92/apb/hair_ponytail.mdl" )
resource.AddFile( "models/jessev92/apb/hair_shoulder1.mdl" )
resource.AddFile( "models/jessev92/apb/hair_shoulder2.mdl" )
resource.AddFile( "models/jessev92/apb/hair_slickedback.mdl" )

-- daft punk
--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/models/zelpa/vhs7/daftpunk/dafthelmet.vmt" )
	resource.AddFile( "materials/models/zelpa/vhs7/daftpunk/dafthelmets.vmt" )
	resource.AddFile( "materials/models/zelpa/vhs7/daftpunk/dafthelmets.vtf" )
	resource.AddFile( "materials/models/zelpa/vhs7/daftpunk/dafthelmets_n.vtf" )
	resource.AddFile( "materials/models/zelpa/vhs7/daftpunk/dafthelmet_animation.vtf" )
	resource.AddFile( "materials/models/zelpa/vhs7/daftpunk/dafthelmet_normal.vtf" )
	resource.AddFile( "materials/models/zelpa/vhs7/daftpunk/dafthelms_animation.vtf" )
	resource.AddFile( "models/zelpa/vhs7/ghelm.mdl" )
	resource.AddFile( "models/zelpa/vhs7/shelm.mdl" )
end

-- speed 2 cruise control
resource.AddFile("sound/taunts/speed2cruisecontrol.ogg")

-- taunts
resource.AddFile("sound/taunts/cantbelieveyouvedonethis.ogg")
resource.AddFile("sound/taunts/thatsprettygood.ogg")

resource.AddFile("sound/taunts/prankpatrol.ogg")

resource.AddFile("sound/taunts/timetoduel.ogg")

resource.AddFile("sound/crates/percussion_1.ogg")
resource.AddFile("sound/crates/percussion_2.ogg")
resource.AddFile("sound/crates/percussion_3.ogg")
resource.AddFile("sound/crates/percussion_4.ogg")

resource.AddFile("materials/vhs7/particles/vhs7_red.vmt")
resource.AddFile("materials/vhs7/particles/vhs7_red.vtf")

--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/models/arizard/crown/crown.vtf" )
	resource.AddFile( "materials/models/arizard/crown/crown_normal.vtf" )
	resource.AddFile( "materials/models/arizard/crown/crown_old.vtf" )
	resource.AddFile( "materials/models/arizard/crown/crown_red.vtf" )
	resource.AddFile( "materials/models/arizard/crown/crown_sheet.vmt" )
	resource.AddFile( "materials/models/arizard/crown/crown_sheet_red.vmt" )
	resource.AddFile( "models/arizard/crown/crown.mdl" )
end
--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/models/weapons/arizard/flag_au.vmt" )
	resource.AddFile( "materials/models/weapons/arizard/flag_au.vtf" )
	resource.AddFile( "materials/models/weapons/arizard/flag_jpn.vmt" )
	resource.AddFile( "materials/models/weapons/arizard/flag_jpn.vtf" )
	resource.AddFile( "materials/models/weapons/arizard/flag_nazi.vmt" )
	resource.AddFile( "materials/models/weapons/arizard/flag_nazi.vtf" )
	resource.AddFile( "materials/models/weapons/arizard/flag_nz.vmt" )
	resource.AddFile( "materials/models/weapons/arizard/flag_nz.vtf" )
	resource.AddFile( "materials/models/weapons/arizard/flag_scot.vmt" )
	resource.AddFile( "materials/models/weapons/arizard/flag_scot.vtf" )
	resource.AddFile( "materials/models/weapons/arizard/flag_uk.vmt" )
	resource.AddFile( "materials/models/weapons/arizard/flag_uk.vtf" )
	resource.AddFile( "materials/models/weapons/arizard/flag_ussr.vmt" )
	resource.AddFile( "materials/models/weapons/arizard/flag_ussr.vtf" )
	resource.AddFile( "materials/models/weapons/arizard/flag_vhs7.vmt" )
	resource.AddFile( "materials/models/weapons/arizard/flag_vhs7.vtf" )
	resource.AddFile( "materials/models/weapons/arizard/flag_vn.vmt" )
	resource.AddFile( "materials/models/weapons/arizard/flag_vn.vtf" )
	resource.AddFile( "models/weapons/arizard/c_buffbanner/c_buffbanner.mdl" )
end
--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/vhs7/particles/100.vmt" )
	resource.AddFile( "materials/vhs7/particles/100.vtf" )
	resource.AddFile( "materials/vhs7/particles/goodshit.vmt" )
	resource.AddFile( "materials/vhs7/particles/goodshit.vtf" )
	resource.AddFile( "materials/vhs7/particles/ok.vmt" )
	resource.AddFile( "materials/vhs7/particles/ok.vtf" )
	resource.AddFile( "materials/vhs7/particles/poop.vmt" )
	resource.AddFile( "materials/vhs7/particles/poop.vtf" )
	resource.AddFile( "materials/vhs7/particles/quinnface.vmt" )
	resource.AddFile( "materials/vhs7/particles/quinnface.vtf" )
	resource.AddFile( "materials/vhs7/particles/rightthere.vmt" )
	resource.AddFile( "materials/vhs7/particles/rightthere.vtf" )
end

--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/models/arizard/sniper_pocketkoala.vmt" )
	resource.AddFile( "materials/models/arizard/sniper_pocketkoala.vtf" )
	resource.AddFile( "models/arizard/sniper_pocketkoala.mdl" )
end

resource.AddFile("materials/vhs7/bsod.vtf")
resource.AddFile("materials/vhs7/nebula1.vtf")
resource.AddFile("materials/vhs7/nebula2.vtf")
resource.AddFile("materials/vhs7/nebula3.vtf")
resource.AddFile("materials/vhs7/nebula4.vtf")
resource.AddFile("materials/vhs7/nebula5.vtf")
resource.AddFile("materials/vhs7/noise.vtf")
resource.AddFile("materials/vhs7/zebra.vtf")
resource.AddFile("materials/vhs7/matrix.vtf")

resource.AddFile("materials/vhs7/bsod.vmt")
resource.AddFile("materials/vhs7/nebula1.vmt")
resource.AddFile("materials/vhs7/nebula2.vmt")
resource.AddFile("materials/vhs7/nebula3.vmt")
resource.AddFile("materials/vhs7/nebula4.vmt")
resource.AddFile("materials/vhs7/nebula5.vmt")
resource.AddFile("materials/vhs7/noise.vmt")
resource.AddFile("materials/vhs7/zebra.vmt")
resource.AddFile("materials/vhs7/matrix.vmt")

resource.AddFile("materials/vhs7/particles/earth.vmt")
resource.AddFile("materials/vhs7/particles/earth.vtf")

resource.AddFile("materials/vhs7/particles/jupiter.vmt")
resource.AddFile("materials/vhs7/particles/jupiter.vtf")

resource.AddFile("materials/vhs7/particles/saturn.vmt")
resource.AddFile("materials/vhs7/particles/saturn.vtf")

resource.AddFile("materials/vhs7/particles/uranus.vmt")
resource.AddFile("materials/vhs7/particles/uranus.vtf")

resource.AddFile("materials/vhs7/particles/neptune.vmt")
resource.AddFile("materials/vhs7/particles/neptune.vtf")

if engine.ActiveGamemode() ~= "terrortown" then

	resource.AddFile("materials/models/arizard/dalek.vmt")
	resource.AddFile("materials/models/arizard/dalek.vtf")
	resource.AddFile("materials/models/arizard/dalek_black.vmt")
	resource.AddFile("materials/models/arizard/dalek_black.vtf")
	resource.AddFile("materials/models/arizard/dalek_normal.vtf")

	resource.AddFile("models/neodement/dalek.mdl")

end

--// File generated by F0x's Resources Generator 3.0.0 \\--


resource.AddFile( "materials/editor/player.vmt" )
resource.AddFile( "materials/editor/player.vtf" )
resource.AddFile( "materials/editor/player_normal.vtf" )
resource.AddFile( "models/player/hands_player.mdl" )
resource.AddFile( "models/player/infoplayerstart.mdl" )

resource.AddFile("materials/vhs7/greengoldstars.vmt")
resource.AddFile("materials/vhs7/greengoldstars.vtf")

--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/models/player/b4p/bobafett/boba_body.vmt" )
	resource.AddFile( "materials/models/player/b4p/bobafett/boba_body.vtf" )
	resource.AddFile( "materials/models/player/b4p/bobafett/boba_hands.vmt" )
	resource.AddFile( "materials/models/player/b4p/bobafett/boba_hands.vtf" )
	resource.AddFile( "materials/models/player/b4p/bobafett/boba_head_revised.vmt" )
	resource.AddFile( "materials/models/player/b4p/bobafett/boba_head_revised.vtf" )
	resource.AddFile( "materials/models/player/b4p/bobafett/boba_jetpack.vmt" )
	resource.AddFile( "materials/models/player/b4p/bobafett/boba_jetpack.vtf" )
	resource.AddFile( "materials/models/player/b4p/chewbacca/chewbacca_1sided.vmt" )
	resource.AddFile( "materials/models/player/b4p/chewbacca/chewbacca_1sided.vtf" )
	resource.AddFile( "materials/models/player/b4p/chewbacca/chewbacca_2sided.vmt" )
	resource.AddFile( "materials/models/player/b4p/chewbacca/chewbacca_2sided.vtf" )
	resource.AddFile( "materials/models/player/b4p/chewbacca/chewbacca_body.vmt" )
	resource.AddFile( "materials/models/player/b4p/chewbacca/chewbacca_body.vtf" )
	resource.AddFile( "materials/models/player/b4p/chewbacca/chewbacca_head.vmt" )
	resource.AddFile( "materials/models/player/b4p/chewbacca/chewbacca_head.vtf" )
	resource.AddFile( "materials/models/player/b4p/chewbacca/chewbacca_sprites.vmt" )
	resource.AddFile( "materials/models/player/b4p/chewbacca/chewbacca_sprites.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/alnewhope.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/alnewhope.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/beltxtras.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/beltxtras.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/darthshing.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/darthshing.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/dbreather.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/dbreather.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/dcape.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/dcape.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/handhope.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/handhope.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/headhope.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/headhope.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/helmethope.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/helmethope.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/hipsvader.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/hipsvader.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/legsvader.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/legsvader.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/shoulderhope.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/shoulderhope.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/torsovader.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/torsovader.vtf" )
	resource.AddFile( "materials/models/player/b4p/vader/vaderface.vmt" )
	resource.AddFile( "materials/models/player/b4p/vader/vaderface.vtf" )
	resource.AddFile( "materials/models/stormt/arms.vmt" )
	resource.AddFile( "materials/models/stormt/arms.vtf" )
	resource.AddFile( "materials/models/stormt/arms_normal.vtf" )
	resource.AddFile( "materials/models/stormt/barneyface.vmt" )
	resource.AddFile( "materials/models/stormt/barneyface.vtf" )
	resource.AddFile( "materials/models/stormt/bmouth.vmt" )
	resource.AddFile( "materials/models/stormt/bmouth.vtf" )
	resource.AddFile( "materials/models/stormt/body-armor.vmt" )
	resource.AddFile( "materials/models/stormt/body-armor.vtf" )
	resource.AddFile( "materials/models/stormt/body-armor_normal.vtf" )
	resource.AddFile( "materials/models/stormt/eyeball_l.vmt" )
	resource.AddFile( "materials/models/stormt/eyeball_l.vtf" )
	resource.AddFile( "materials/models/stormt/eyeball_r.vmt" )
	resource.AddFile( "materials/models/stormt/eyeball_r.vtf" )
	resource.AddFile( "materials/models/stormt/helmet.vmt" )
	resource.AddFile( "materials/models/stormt/helmet.vtf" )
	resource.AddFile( "materials/models/stormt/helmet_normal.vtf" )
	resource.AddFile( "materials/models/stormt/pupil_l.vmt" )
	resource.AddFile( "materials/models/stormt/pupil_l.vtf" )
	resource.AddFile( "materials/models/stormt/pupil_r.vmt" )
	resource.AddFile( "materials/models/stormt/pupil_r.vtf" )
	resource.AddFile( "models/player/b4p/b4p_bobafett.mdl" )
	resource.AddFile( "models/player/b4p/b4p_chewbacca.mdl" )
	resource.AddFile( "models/player/b4p/b4p_vader.mdl" )
	resource.AddFile( "models/player/stormt.mdl" )
end

resource.AddFile( "sound/taunts/donotfeed.ogg" )
